### PR TITLE
v2.1.0 Database Refactor

### PR DESCRIPTION
**Pull request by ThatsLiamS**
This **Pull Request** refactors Coin Flipper's database usage and management: from implementing a new cache system to redesigning the Schemas, there has been a full overhaul.

### Commits
- e2b67f05ac8091c6cfd50d0667f341d23a620c73 **Refactor(Schema):** created new database model and schemas
- c88bdbc4d0bee076ff4ca6847f7e1de0a13f6613 **Feat(Cache):** created database methods and cache system
- f9ba24254e9c989d1406c6956a65a18aa4e73205 **Feat():** added database reformatter
- d6ef203415c5a37edbaee5226c6abe555bc417c9 **Refactor(Commands):** updated commands to the new schema
- 17894be62cf82e15530ca121ad5ba56c8204e5dc **Refactor(Files):** emojis, badges, constant values

Along with 1ce47584c02cb1e3d985452fe2c0a952af53af77 110bc74b2080d9cf8f371c4daebe8e3c25e1fc6a c087fa04fce3dd619ce0d42478da0f3faef07f87 labelled as **bug fixes**

### Changes
- Created branch new schemas/default data (`src/util/Database Schema.js`)
- Created a new algorithm to transform old schema data into the new model (`src/util/reformatData.js`)
- Created a new cache system, using [Discord Collections](https://discord.js.org/#/docs/collection/main/class/Collection) to reduce database reads
- Manually changed all files to use the new Database Model
- Removed old files (`src/util/emojis.js`, `src/util/flips`, along with the `src/util/defaultData/*`)
- Fixed the cooldown system
- Changed `Achievement Mail` to sending `DMs` instead

### CODE REVIEW

**Review by SuperPhantomUser — APPROVED** [review]
Huh look at that I approved it

**Comment by Non94305** [comment]
Pls fix the dynamite and badge command bug

**Comment by Non94305** [comment]
And the items bug you have gaved discription that if we had a item in our inv or use it wee will get some extra coins but its not working fix it

**Comment by ThatsLiamS** [comment]
This PR has been resolved, if you have a problem or have seen a bug within Coin Flipper, please fill out an [Issue Report](https://github.com/Coin-Flipper/Coin-Flipper/issues/new?assignees=ThatsLiamS&labels=bug&template=bug-report.md&title=)

**Pull request merged**
